version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: cabello
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # - FERNET_KEY="C7rSqWZE76-Xox4VtLIbFWsLTsr1xIWq21zDEgpSxWs="
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./test:/usr/local/airflow/test
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
            - ./ingest_scripts:/usr/local/ariflow/ingest_scripts
        ports:
            - "8080:8080"
            # - "5432:5432"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
